MODEL:
  TYPE: 'VM_ASR'
  NAME: 'Pytorch_CUDA_mix_BCHW_0'
  VSSM:
    DIMS: 16

TRAIN:
  EARLY_STOPPING: 10
  LOW_FREQ_REPLACEMENT: True
  ADVERSARIAL:
    ENABLE: True
    DISCRIMINATORS: ["mpd"]
    STFT_LOSS:
      EMPHASIZE_HIGH_FREQ: False

DATA:
  BATCH_SIZE: 15
  TARGET_SR: 16000
  USE_QUANTITY: 1.0
  VALID_SPLIT: 0.1
  WEIGHTED_SR:
    ENABLE: False
  LPF:
    MULTIFILTER: True

DEBUG: False

WANDB:
  ENABLE: True
  TAGS: ["16k", "Data_1.0", "MPD"]